# Uber-go

run:
  timeout: 5m
  modules-download-mode: mod
  skip-dirs:
    - docs

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/gvencadze/swe-basic